### ISSUE TITLE
Publish in NextCloud Appstore

### ISSUE THREAD

**Issue by genofire** [UP-NextPush/server-app#1]
https://apps.nextcloud.com/?search=NextPush

**Comment by p1gp1g** [comment]
Waiting for a signed certif https://github.com/nextcloud/app-certificate-requests/pull/462

**Comment by witchent** [comment]
When can we expect it in the appstore now that the certificate is there? Thanks for your work by the way

**Comment by genofire** [comment]
Is in store, now.

https://apps.nextcloud.com/apps/uppush

but still no searchable with the Term `Nextpush`:
https://apps.nextcloud.com/?search=NextPush

**Comment by witchent** [comment]
Oh god, my bad, should have looked harder.
It is searchable, its just that the name got no NextPush in it :D
Guess this issue can be closed though. Thanks again for all your work.

**Comment by genofire** [comment]
Does we want to keep this issue open till it is searchable with NextCloud (by put it in description or so)?

Otherwise, yes the origin meaning of this issue solved.

I believe that should decide by the maintainer.

**Comment by p1gp1g** [comment]
I didn't notice it was in the store :laughing: .

I keep this issue until I update the description.

**Comment by p1gp1g** [comment]
It is now searchable https://apps.nextcloud.com/?search=NextPush
