### ISSUE TITLE
I can't register my phone

### ISSUE THREAD

**Issue by kakuy** [UP-NextPush/server-app#11]
When I try to login using the account from Nextcloud app, UP-NextPush/android crashes and nginx log shows this:

```
"PUT /index.php/apps/uppush/device? HTTP/1.1" 200 66 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.19.1"
"GET /index.php/apps/uppush/device/{{ALWAYS_THE_SAME_UUID_HERE}} HTTP/2.0" 200 98 "-" "okhttp/4.9.3"
```
But nothing else happens: No registered devices server side, no applications on the android side and not notifications.

I switched to https://gitlab.com/Nextcloud-Push and it works perfectly: connection succeeds immediately notifications arrive instantly and are even queued if I disconnect my phone and are delivered as soon as it comes back. So I'd say php/nginx configuration is ok.

**Comment by p1gp1g** [comment]
Which version of the server app [1] do you use ?
Which version of the android app do you use ?
Is the server app activated ?
Do you have android logs ?
Do you have nextcloud errors log ?

[1] https://apps.nextcloud.com/apps/uppush

**Comment by kakuy** [comment]
>Which version of the server app [1] do you use ?

https://apps.nextcloud.com/apps/uppush 1.0.0 on Nextcloud 23.0.3

>Which version of the android app do you use ?

https://github.com/UP-NextPush/android 1.3.0 (tested the github release and F-Droid release with the same results)

>Is the server app activated ?

Yes

>Do you have android logs ?

No, I don't know how to get them, I don't have a rooted phone.

>Do you have nextcloud errors log ?

No.

**Comment by kakuy** [comment]
After leaving it there for about half a day, it now uppush shows now one device registered but when I try to test push notifications with `occ notification:test-push` I get:
```
Trying to push to 1 devices

Language is set to es_ES
Private user key size: 1704
Public user key size: 451
Identified 0 Talk devices and 1 others.

Device token:59
Device public key size: 450
Data to encrypt is: {"nid":17728,"app":"admin_notifications","subject":"Testing push notifications","type":"admin_notifications","id":"62592f2a"}
Signed encrypted push subject
Push notification sent but response was not parsable, using an outdated push proxy? [[https://](https://{my nextcloud host}/index.php/apps/ssepush]:
```
Followed by the actual html code from my nextcloud's login page.

Something is not right with my setup :sob:

**Comment by p1gp1g** [comment]
SSEPush is another project. NextPush is not (yet?) designed to receive nextcloud notifications but to receive notifications for applications using unifiedpush

**Comment by kakuy** [comment]
Ah... So I completely misunderstood the target of this application!
Sorry about that!

I close this issue because... well... these are not the droid I was looking for. :man_shrugging:
