### ISSUE TITLE
Notification debugging problem

### ISSUE THREAD

**Issue by akallabeth** [UP-NextPush/server-app#13]
Hi,
I´ve set up next push with my nextcloud instance as by README.

1. Server side I´ve installed the current version from nextcloud apps (not from github directly)
2. Server is using apache and redis (debian 11 system)
3. Client side I´ve installed from `F-Droid` 
4. Applications register (fluffy chat, fedilab and UP-Example)
5. If I try `UP-Example` I never receive a notification though...

Sorry, could not find a good `FAQ` of what else to check, so asking here.
any help appreciated :)

**Comment by p1gp1g** [comment]
Are you connected on the android app ?
Do you see "NextPush is disconnected" notification ?
Do you see `{"unifiedpush":{"gateway":"matrix"}}` here : https://your.domain.tld/apps/uppush/gateway/matrix

**Comment by akallabeth** [comment]
@p1gp1g thank you for the help, I´ve just figured out what the problem is.
Notifications are broken in my wlan (where the nextcloud instance is running) but are working form mobile/external networks.

**Comment by p1gp1g** [comment]
That sounds like a [hairpinning](https://en.wikipedia.org/wiki/Hairpinning) issue

**Comment by akallabeth** [comment]
@p1gp1g maybe, need to check if the device is properly using my internal resolvers, where the dns name is mapped directly to the correct IP.
Anyway, does not look like a issue of the project, so closing and thanks for the help
