### ISSUE TITLE
"Connecting to redis without password" while reading response header from upstream

### ISSUE THREAD

**Issue by ne20002** [UP-NextPush/server-app#19]
I get a number of log lines in nginx error log

```2022/07/02` 09:03:06 [error] 82#82: *362 FastCGI sent in stderr: "PHP message: Nextcloud/UnifiedPushProvider: Connecting to redis without password" while reading response header from upstream, client: 192.168.xxx.xxx, server: , request: "GET /index.php/apps/uppush/device/xxxxxxxxxxxx HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx.xxxx.xx"```

but it seems as if the android app is connected.

How to get rid of this error?

**Comment by p1gp1g** [comment]
That's an error logged to inform admin. I can remove it if it is annoying > https://github.com/UP-NextPush/server-app/blob/main/lib/Controller/UnifiedPushProviderController.php#L49

**Comment by ne20002** [comment]
If this is not an error, I recommend to remove it. It's annoying. 
Ususally admins know if they have set up local Redis with password or not. I believe for most small installation and those with docker where you have redis only accessible in local/isolated network, passwords for redis are not needed.
