### ISSUE TITLE
[Feature request] Send push notification through HTTP

### ISSUE THREAD

**Issue by koug44** [UP-NextPush/server-app#23]
Hello,

This is not a bug. I want to replace a Gotify server with a NextPush one but I can't find any information on how to send notification through a simple HTTP request (curl or httpie)

I didn't find a better canal for asking you this :-/

Damien

**Comment by p1gp1g** [comment]
NextPush works only as a unifiedpush distributor, to forward notifications to other applications. It does not have this feature (showing a notification).

But it is possible to implement it quite easily if it is needed. If I do so, it will just handle simple notifications, raw text without all the features ntfy has :)

**Comment by koug44** [comment]
Oh ok, thanks for the explaination. So I guess I’ve to stick with both services for a while

**Comment by p1gp1g** [comment]
You may want to keep that issue open and change the title from *Documentation request* to *Feature request*

**Comment by koug44** [comment]
Some examples of what the feature could look like are available on the Gotify documentation:

https://gotify.net/docs/pushmsg

**Comment by p1gp1g** [comment]
This is possible since version 1.7.0 of NextPush (Android), so I'm closing the issue :)
