### ISSUE TITLE
Redis username and connection over TLS unsupported

### ISSUE THREAD

**Issue by bastei** [UP-NextPush/server-app#24]
Since version 6 Redis supports Access Control Lists (ACLs) where usernames can be defined. NextPush should support usernames, [like Nextcloud does](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/caching_configuration.html#id2).

Additionally, Nextcloud can be configured to connect to Redis via TLS, which is not respected in NextPush.

**Comment by p1gp1g** [comment]
Fixed with d9aeab0cb0eab1f727363cef8d786c182f047fd1 included in release 1.1.0
