### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by p-bo** [UP-NextPush/server-app#25]
Hello,
Would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html
...and make your app more accessible for non-English speakers please?

Thanks :-)

**Comment by p1gp1g** [comment]
That's a good idea. Help is welcome :)

**Comment by p-bo** [comment]
> Help is welcome

Don't worry, it is not rocket science. Just open new issue on https://github.com/nextcloud/docker-ci/issues/new/choose (choose Request translations). And you will get checklist as for example this: https://github.com/nextcloud/docker-ci/issues/426 and regarding technical implementation details, @nickvergessen seems to be very kind guide trough this process - just open mentioned issue, try your best to do what is stated there and most importantly - actively communicate and cooperate with Joas. That's it.

**Comment by p1gp1g** [comment]
Done: https://codeberg.org/NextPush/uppush/commit/21dc2e69c3d19fca9cea4e3c9e4dd194745cf5b0
