### ISSUE TITLE
Matrix push gateway is not working anymore

### ISSUE THREAD

**Issue by niks255** [UP-NextPush/server-app#27]
Seems like the client requires a new field in JSON response. Should be an easy fix.

![изображение_2022-11-05_104422853](https://user-images.githubusercontent.com/4942241/200109357-d470d97a-a05f-4ba6-84eb-9adeb89cc0c1.png)

**Comment by p1gp1g** [comment]
Could you test that script: https://github.com/UP-NextPush/server-app/blob/main/script/tests.sh

**Comment by niks255** [comment]
> Could you test that script: https://github.com/UP-NextPush/server-app/blob/main/script/tests.sh

Yep.

[+] Checking URL
[*] Nextcloud server found.
[+] Checking matrix gateway
[!] Matrix gateway is not setup. cf. https://github.com/UP-NextPush/server-app#gateways

Although it shows exactly what the script expects https://ownserver.duckdns.org/_matrix/push/v1/notify/

**Comment by niks255** [comment]
Okay, seems like this issue was related to nginx. The trailing slash at the end was an issue, for some reason it didn't work without it. And browser kept adding it when I opened the URL, so I never noticed the problem.
This can now be closed.
