### ISSUE TITLE
Different domains for nextcloud and matrix

### ISSUE THREAD

**Issue by sdfg2** [UP-NextPush/server-app#29]
How to configure for this?

**Comment by p1gp1g** [comment]
What do you mean exactly ? matrix.domain.tld for synapse and nextcloud.domain.tld for nextcloud (this is always the case) ? Or matrix.gateway.domain.tld for the matrix gateway and nextcloud.domain.tld for nextcloud (this is impossible) ?

**Comment by sdfg2** [comment]
domain.tld for matrix, and cloud.domain.tld in this particular case.

**Comment by p1gp1g** [comment]
You can use a reverse proxy like nginx to do this. But your need is not related to this nextcloud applicatio

**Comment by p1gp1g** [comment]
Not related to nextpush
