### ISSUE TITLE
Table \"oc_uppush_applications\" has no primary key and therefor will not behave sane in clustered setups. This will throw an exception and not be installable in a future version of Nextcloud.

### ISSUE THREAD

**Issue by provokateurin** [UP-NextPush/server-app#34]
Error message appears in the server logs.

**Comment by p1gp1g** [comment]
Nextcloud version ?

**Comment by provokateurin** [comment]
25 Docker image

**Comment by p1gp1g** [comment]
During the app installation ?

**Comment by provokateurin** [comment]
No I think at every request that is made.

**Comment by provokateurin** [comment]
The docker image uses sqlite by default, so that might have some effect on this.

**Comment by Lastaapps** [comment]
Is this error I'm getting in the admin while trying to install the UnifiedPush Provider plugin related to this issue?

25.0.4, Docker alpine, Postgres alpine 15 latest

```
An exception occurred while executing a query: SQLSTATE[42501]: Insufficient privilege: 7 ERROR: permission denied for schema public LINE 1: CREATE TABLE oc_uppush_applications (device_id VARCHAR(255) ... ^
```
Thanks

**Comment by provokateurin** [comment]
No that is something different. Your problem is database permissions while this is message is just a warning printed by nextcloud.

**Comment by p1gp1g** [comment]
@provokateurin Do you use docker-compose ? To have the same setup as you

**Comment by provokateurin** [comment]
No, just plain dockerfile: https://github.com/provokateurin/nextcloud-neon/blob/main/tool/Dockerfile.dev
I saw the warnings in the logs when I was adding my unit tests for the API of this app.

**Comment by p1gp1g** [comment]
Is the error thrown when you run the tests.sh script ? Or only during the installation ? Also, you are using sqlite right ?

**Comment by provokateurin** [comment]
During tests, not installation and sqlite, yes.
