### ISSUE TITLE
Compatible with NC 26

### ISSUE THREAD

**Issue by provokateurin** [UP-NextPush/server-app#38]
Currently 25 is the maximum version. Please bump to 26 to allow the latest version.

**Comment by p1gp1g** [comment]
I was waiting for the nextcloud:26 container. I'm publishing it soon

Le 23 mars 2023 10:12:22 GMT+01:00, Kate ***@***.***> a écrit :
>Currently 25 is the maximum version. Please bump to 26 to allow the latest version.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/UP-NextPush/server-app/issues/38
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by provokateurin** [comment]
I think for the next time it would be nice to already test it with the RC's, because then it can already be compatible at the new release. RC3 should be exactly the same as the final release if everything goes well.

**Comment by herrwusel** [comment]
For what it's worth: I enabled the app on NC 26 and just got a notification.

**Comment by provokateurin** [comment]
I also doubt there are incompatibilities, but it should still be checked

**Comment by provokateurin** [comment]
I can also confirm it works just fine on 26

**Comment by p1gp1g** [comment]
Done with 1.3.0

**Comment by p1gp1g** [comment]
@provokateurin 
> I think for the next time it would be nice to already test it with the RC's, because then it can already be compatible at the new release. RC3 should be exactly the same as the final release if everything goes well.

Just for your information, I opened an issue before NC26 was released in order to get a RC container image to upgrade the app before the NC release: https://github.com/nextcloud/docker/issues/1910 ; But they don't plan to do beta/rc container :/

I may ask for help to test the upgrade before the release next time :)
