### ISSUE TITLE
[Question] Use with unifiedpush-cli

### ISSUE THREAD

**Issue by loxK** [UP-NextPush/server-app#40]
Hello,

I want to send notifications from my server to my phone using [unifiedpush-cli](https://github.com/aerogear/unifiedpush-cli), is that possible?

**Comment by p1gp1g** [comment]
This script is not related to UnifiedPush (.org). If you want to send a notification to your phone, you can "Add notification channel" then you can use curl : `curl --data "I want to push this" https://my.endpoint.tld/apps/foo`

**Comment by loxK** [comment]
Allright. But what is the endpoint on a Nextcloud install ?

**Comment by p1gp1g** [comment]
To get one:
- Open NextPush (android)
- Open the 3 dots menu
- Click on "Add notification channel"
- Enter a title
- Long click on the line with this title
- Click on copy

**Comment by loxK** [comment]
Thanks
