### ISSUE TITLE
Use capabilities instead of check endpoint

### ISSUE THREAD

**Issue by provokateurin** [UP-NextPush/server-app#42]
Clients can currently detect if the app is installed via the check endpoint. That is an unusual pattern and apps should instead expose capabilities to let clients know that they are available. Please consider exposing a capability and deprecating and eventually removing the check endpoint.

**Comment by p1gp1g** [comment]
Do you have an example of a nextcloud app doing it ?

**Comment by provokateurin** [comment]
Almost every app does it, for example https://github.com/nextcloud/server/blob/master/apps/user_status/lib/Capabilities.php

**Comment by p1gp1g** [comment]
And android side, what should I do ?

**Comment by provokateurin** [comment]
You need to query the capabilities endpoint as described here: https://github.com/nextcloud/server/blob/687d7686c19d03d7a2baceeeb0980dc30e28972b/core/openapi.json#L1207. Of course you will still have to query the check endpoint as a fallback for a while.

**Comment by p1gp1g** [comment]
Capabilities added: https://codeberg.org/NextPush/uppush/commit/42d385ad1866a9c2c15187f66d2c7b1db147a395
