### ISSUE TITLE
Change to Server Sent Events (SSE)

### ISSUE THREAD

**Issue by xundeenergie** [UP-NextPush/server-app#5]
Tutanota explained, how they did notification to replace GCM/FCM with an old protocol SSE (Server Sent Events) in this german article.

https://f-droid.org/de/2018/09/03/replacing-gcm-in-tutanota.html

Do you think, it could be implemented

**Comment by p1gp1g** [comment]
Notifications are sent via SSE already

**Comment by xundeenergie** [comment]
Ok... sounds good. And the "rest" of this article... do you understand german. Or should i translate it?

Tutanota found a solution to get notificated without a permanent notification to keep the app awake.

**Comment by p1gp1g** [comment]
Thanks, I have translated it : mainly, they restart their service every 15 min. But it won't be a solution for up distribs : optimization don't stop being harder and restrictions increase with the android versions. So the remaining notification will do the job :) (It is possible to hide it)
